# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Jhon Fredy Beltrán León
title: Junior Software Engineer at PayU LATAM
email: jbeltranleon@gmail.com
website: jbeltranleon.github.io

# Social links
twitter_username: jbeltranleon
github_username:  jbeltranleon
# dribbble_username: jekyll
facebook_username: jbeltranleon
# flickr_username: jekyll
instagram_username: jbeltranleon
linkedin_username: jbeltranleon
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpeg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Jhon Fredy and I'm a Junior Software Engineer oriented Machine Learning.

  I love public speaking and sharing everything I have learned. All people deserve to be happy and if from my work I can help, I will be happy to do so. 
  
  I am most skilled in: <mark>Java</mark> and <mark>Python</mark> using AI Frameworks such <mark>Keras</mark> and <mark>SKLearn</mark> 

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in AI and software engineering some of my other interests and hobbies are:
   - Play tennis
   - Learn languages

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
