# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Jhon Fredy Beltrán León
title: Junior Data Engineer at PayU LATAM
email: jbeltranleon@gmail.com
website: jbeltranleon.github.io

# Social links
twitter_username: jbeltranleon
github_username:  jbeltranleon
# dribbble_username: jekyll
facebook_username: jbeltranleon
# flickr_username: jekyll
instagram_username: jbeltranleon
linkedin_username: jbeltranleon
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpeg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Jhon Fredy and I'm a Junior Data Engineer who loves Machine Learning.

  I love public speaking and sharing everything I have learned. All people deserve to be happy and if I can help, I will be happy to do so. 
  
  I am most skilled in: <mark>Python</mark> and <mark>Java</mark> 

  Some of my hobbies are:
   - Play tennis and video games
   - Learn languages
   - Play the guitar

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
more_title: Honors & Awards

more_content: | # this will include new lines to allow paragraphs
  - 1st Place on the PayU Global Hackathon 2020 [Itzamná]
  - 2nd Place on Techstars Startup Weekend Colombia 2018 UCundinamarca Chía [Quickpets]

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
